//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HG100.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plant
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plant()
        {
            this.UserFavorited = new HashSet<MyGarden>();
            this.UserSelected = new HashSet<MyGarden>();
        }
    
        public int Id { get; set; }
        public string Type { get; set; }
        public string Shade { get; set; }
        public string Bloom { get; set; }
        public int Zone { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public string PlantName { get; set; }
        public string Imagefilename { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyGarden> UserFavorited { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MyGarden> UserSelected { get; set; }
    }
}
